#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
export BLUE='\033[1;94m'
export RED='\033[1;91m'

title="$RED 		Hi BRO!) it's proxy2tun \n"
prompt=
options=("Proxy->System" "Proxy->namespace" "Proxy->System->namespace" "Proxy->namespace->Wi-Fi" "Proxy->System->namespace->Wi-Fi" "Settings")

clear
echo -e -n  "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in

    1 ) clear
		echo -e -n "$BLUE Proxy->System \n"
		src/proxyON_sys
		clear
		src/proxyOFF_sys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	2 ) clear
		echo -e -n "$BLUE Proxy->namespace \n"
		src/proxyON_name
		clear
		src/proxyOFF_name
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	3 ) clear
		echo -e -n "$BLUE Proxy->System->namespace \n"
		src/proxyON_name_sys
		clear
		src/proxyOFF_name_sys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	4 ) clear
		echo -e -n "$BLUE Proxy->namespace->Wi-Fi \n"
		src/proxyON_name_wifi 
		clear
		src/proxyOFF_name_wifi
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	5 ) clear
		echo -e -n "$BLUE Proxy->System->namespace->Wi-Fi \n"
		src/proxyON_name_sys_wifi 
		clear
		src/proxyOFF_name_sys_wifi 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    6 ) clear
		echo -e -n "$BLUE Settings \n"
		src/settings
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;

    $(( ${#options[@]}+1 )) ) clear; break;;
    *) echo -e -n  "$RED Invalid option. Try another one. \n";continue;;

    esac

done
