#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
echo "This Is configuration file DON'T REMOVE IT" | cat > variables.conf

read -p "Enter Proxy IP (89.243.157.254) > " remote_ip
echo $remote_ip | cat >> variables.conf

read -p "Enter Proxy port (1080) > " remote_port
echo $remote_port | cat >> variables.conf

read -p "Proxy with login pass? (y/n) > " proxy_logpass

if [[ ! $proxy_logpass =~ ^[Nn]$ ]]; 
then read -p "Enter Proxy login (user) > " login
	echo $login | cat >> variables.conf
	read -p "Enter Proxy password (pass) > " pass
	echo $pass | cat >> variables.conf
	sudo sed -i '15c\log_pass=\"--username $login --password $pass\"'  proxyON_sys
	sudo sed -i '15c\log_pass=\"--username $login --password $pass\"' proxyON_name
	sudo sed -i '15c\log_pass=\"--username $login --password $pass\"' proxyON_name_sys
	sudo sed -i '15c\log_pass=\"--username $login --password $pass\"' proxyON_name_wifi
	sudo sed -i '15c\log_pass=\"--username $login --password $pass\"' proxyON_name_sys_wifi

elif [[ ! $proxy_logpass =~ ^[Yy]$ ]]; 
then echo   | cat >> variables.conf
	echo   | cat >> variables.conf
	sudo sed -i '15c\log_pass=' proxyON_sys
	sudo sed -i '15c\log_pass=' proxyON_name
	sudo sed -i '15c\log_pass=' proxyON_name_sys
	sudo sed -i '15c\log_pass=' proxyON_name_wifi
	sudo sed -i '15c\log_pass=' proxyON_name_sys_wifi
fi

read -p "Enter bind interface (veth1) > " bind_iface
echo $bind_iface | cat >> variables.conf

read -p "Enter badvpn interface (tun11658) > " bad_tun
echo $bad_tun | cat >> variables.conf

read -p "Enter name of namespace (ns1) > " NS
echo $NS | cat >> variables.conf

read -p "Enter name of namespace link interface (veth1) > " VETH
echo $VETH | cat >> variables.conf

read -p "Enter name of interface in namespace (peth0) > " VPEER
echo $VPEER | cat >> variables.conf

read -p "Enter namespace link interface IP (10.200.1.1) > " VETH_ADDR
echo $VETH_ADDR | cat >> variables.conf

read -p "Enter interface in namespace IP (10.200.1.2) > " VPEER_ADDR
echo $VPEER_ADDR | cat >> variables.conf

read -p "Enter name of Wi-Fi interface (wlan1) > " wifi_iface
echo $wifi_iface | cat >> variables.conf

read -p "Enter hotspot name (HotSpot) > " wifi_name
echo $wifi_name | cat >> variables.conf

read -p "Enter hotspot password (minimum 8 characters) > " wifi_pass
echo $wifi_pass | cat >> variables.conf

read -p "Enter hotspot region (BZ) > " wifi_reg
echo $wifi_reg | cat >> variables.conf

read -p "Enter hotspot MAC (46:03:08:01:89:55) > " wifi_mac
echo $wifi_mac | cat >> variables.conf

